export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/",
  PROJECTS: "/projects",
  PROJECT_NEW: "/projects/new",
  PROJECT_EDIT: (id: string) => `/projects/${id}/edit`,
  SKILLS: "/skills",
  SKILL_NEW: "/skills/new",
  SKILL_EDIT: (id: string) => `/skills/${id}/edit`,
  EXPERIENCE: "/experience",
  EXPERIENCE_NEW: "/experience/new",
  EXPERIENCE_EDIT: (id: string) => `/experience/${id}/edit`,
  EDUCATION: "/education",
  EDUCATION_NEW: "/education/new",
  EDUCATION_EDIT: (id: string) => `/education/${id}/edit`,
  CERTIFICATES: "/certificates",
  CERTIFICATE_NEW: "/certificates/new",
  CERTIFICATE_EDIT: (id: string) => `/certificates/${id}/edit`,
  RESUME: "/resume",
  MESSAGES: "/messages",
  MESSAGE_DETAIL: (id: string) => `/messages/${id}`,
  SETTINGS: "/settings",
  PROFILE: "/profile",
} as const;
